### ISSUE TITLE
How to add a new device via Android/iOS application instead of through the CP?

### ISSUE THREAD

**Issue by sandy-abrightmind** [boboldehampsink/pushnotifications#1]
Hi

I've been trying to figure out how to add a new device token to an app via Android/iOS code instead of through the CraftCMS CP?

Can I add a new device token via URL?

If so, what is an example URL with the POST parameters?

Thanks!
Sandy Davis

**Comment by boboldehampsink** [comment]
You have to POST to actions/pushNotifications/registerDevice with:

``` json
{
    'app': 'app_handle',
    'platform': 'ios/android',
    'registrationId': 'token'
}
```

P.s. send these as POST params, not as JSON ;-)

**Comment by sandy-abrightmind** [comment]
I'm still not doing something right. =(I'm testing via Postman.Is the correct URL: localhost/CraftCMS/public/admin/actions/pushNotifications/registerDevice ?I've attached a screenshot of my postman configuration.Thanks!SandyOn October 15, 2015 at 8:21 AM Bob Olde Hampsink notifications@github.com wrote:You have to POST to actions/pushNotifications/registerDevice with:{
    'app': 'app_handle',
    'platform': 'ios/android',
    'registrationId': 'token'
}P.s. send these as POST params, not as JSON ;-)—Reply to this email directly or view it on GitHub.

**Comment by boboldehampsink** [comment]
Sorry, I didn't get the screenshot

**Comment by sandy-abrightmind** [comment]
Yeah, I just realized that it didn't send it via the email. 
Here it is.
![postman_config_post](https://cloud.githubusercontent.com/assets/8899994/10515231/0cc4e4aa-7318-11e5-96f3-7a6e7495f2f6.png)

**Comment by boboldehampsink** [comment]
Ah, you're sending them as Headers instead of as Post values

**Comment by sandy-abrightmind** [comment]
Oops.

I added them as params and it still doesn't work. =(

If I type the url that it created into an address bar, it gives me "Page Not Found" error... so maybe it's the URL that I have wrong?

![post_man_config_2](https://cloud.githubusercontent.com/assets/8899994/10515557/a4a20d10-7319-11e5-91a1-9d29c3400c50.png)

**Comment by boboldehampsink** [comment]
Yeah sorry, the url should be /actions/pushNotifications/devices/registerDevice

**Comment by sandy-abrightmind** [comment]
It works if I submit the URL to the browser but it doesn't add a new device if I do it from postman.

http://localhost/CraftCMS/public/admin/actions/pushNotifications/devices/registerDevice?app=gcm&platform=android&registrationId=test9823

Any ideas why it won't work from postman?

I'm assuming that I won't run into any authentication problems when I try to submit it from my Android/iOS code?

**Comment by boboldehampsink** [comment]
Because you have the variables both in the url and in the post body?

**Comment by sandy-abrightmind** [comment]
I don't understand what you mean by that. I have postman configured with the exact same url as above and it doesn't work. I was just curious if that's because it doesn't know the login credentials for CraftCMS. And maybe in the browser, the credentials are cached?

**Comment by boboldehampsink** [comment]
No, the call can always be made anonymously.

Your url should not have "?app=gcm&platform=android&registrationId=test9823" in it, these should be POSTed

**Comment by sandy-abrightmind** [comment]
It did that automatically when I set the params in Postman.

When I ran my url in the browser, it returned success as true for that url.

And it added the new device token to Craft when I ran that url in the browser.

However, if I run it via Postman, it does not add the new device token.

**Comment by boboldehampsink** [comment]
It only does that automatically when you've selected GET instead of POST

**Comment by sandy-abrightmind** [comment]
Here is a screenshot of my postman configuration.

I have it selected as POST and it still adds the params to the URL.

![post_man_params_configuration](https://cloud.githubusercontent.com/assets/8899994/10517489/939d7f3c-7322-11e5-9f84-4856b90d8b02.png)

**Comment by boboldehampsink** [comment]
Ok, looks like you're posting with get variables, but empty post body. Can you look inside the Body tab?

**Comment by sandy-abrightmind** [comment]
The body tab was empty.

Even when I add the information there, it doesn't work in Postman.

**Comment by sandy-abrightmind** [comment]
Okay, so if I log out of CraftCMS then the URL that worked in the browser doesn't work. It takes me to the login page of craft. =(

**Comment by sandy-abrightmind** [comment]
I figured it out!!!

It was my URL.
Here is a new screenshot:

![post-man_config_successful](https://cloud.githubusercontent.com/assets/8899994/10519231/7feeb76e-732a-11e5-8c6d-69cbbbda67f5.png)

Thank you for your help! =)

**Comment by boboldehampsink** [comment]
Nice! That was actually what I was trying to say ;-)

**Comment by sandy-abrightmind** [comment]
Yeah, I'm new to CraftCMS so I wasn't sure how to access it. =) Thank you for all of your help!!
